language: node_js
sudo: required
dist: trusty

node_js:
	- "4"
	- "5"
	- "6"

cache:
	yarn: true
	directories:
		- node_modules

before_install:
	- nvm install 6.9.1
	- nvm use 6.9.1
	- sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
	- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
	- sudo apt-get update -qq
	- sudo apt-get install -y -qq yarn

install: yarn install && yarn run lint && yarn run build:prod

branches:
	only:
		- master
